"""initial schema

Revision ID: 3067dae7d76d
Revises: 
Create Date: 2026-06-12 19:10:54.311085

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '3067dae7d76d'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_id_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('internal_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('external_id', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'source', 'external_id')
    )
    op.create_table('ingestion_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Text(), server_default='running', nullable=False),
    sa.Column('fixtures_updated', sa.Integer(), server_default='0', nullable=False),
    sa.Column('insights_generated', sa.Integer(), server_default='0', nullable=False),
    sa.Column('reconciliation_flags', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('code', sa.Text(), nullable=True),
    sa.Column('group_label', sa.Text(), nullable=True),
    sa.Column('flag_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_table('fixtures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.Text(), nullable=False),
    sa.Column('home_team_id', sa.Integer(), nullable=True),
    sa.Column('away_team_id', sa.Integer(), nullable=True),
    sa.Column('kickoff_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('venue', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('group_label', sa.Text(), nullable=True),
    sa.Column('round', sa.Text(), nullable=True),
    sa.Column('minute', sa.Integer(), nullable=True),
    sa.Column('verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mismatch_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_index('idx_fixtures_away_team', 'fixtures', ['away_team_id'], unique=False)
    op.create_index('idx_fixtures_home_team', 'fixtures', ['home_team_id'], unique=False)
    op.create_index('idx_fixtures_kickoff', 'fixtures', ['kickoff_at'], unique=False)
    op.create_index('idx_fixtures_status', 'fixtures', ['status'], unique=False)
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_table('standings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('group_label', sa.Text(), nullable=False),
    sa.Column('played', sa.Integer(), server_default='0', nullable=False),
    sa.Column('won', sa.Integer(), server_default='0', nullable=False),
    sa.Column('drawn', sa.Integer(), server_default='0', nullable=False),
    sa.Column('lost', sa.Integer(), server_default='0', nullable=False),
    sa.Column('goals_for', sa.Integer(), server_default='0', nullable=False),
    sa.Column('goals_against', sa.Integer(), server_default='0', nullable=False),
    sa.Column('goal_diff', sa.Integer(), sa.Computed('goals_for - goals_against', ), nullable=False),
    sa.Column('points', sa.Integer(), server_default='0', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id')
    )
    op.create_index('idx_standings_group', 'standings', ['group_label'], unique=False)
    op.create_table('ai_insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fixture_id', sa.Integer(), nullable=True),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('prompt_version', sa.Text(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fixture_id', 'state')
    )
    op.create_index('idx_ai_insights_fixture', 'ai_insights', ['fixture_id', 'state'], unique=False)
    op.create_table('goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fixture_id', sa.Integer(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('player_name', sa.Text(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('minute', sa.Integer(), nullable=True),
    sa.Column('type', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fixture_id', 'player_name', 'minute', 'type')
    )
    op.create_table('lineups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fixture_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('player_name', sa.Text(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('position', sa.Text(), nullable=True),
    sa.Column('is_starter', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('formation', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fixture_id', 'team_id', 'player_name')
    )
    op.create_table('match_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fixture_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('possession', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('shots', sa.Integer(), nullable=True),
    sa.Column('shots_on_target', sa.Integer(), nullable=True),
    sa.Column('corners', sa.Integer(), nullable=True),
    sa.Column('fouls', sa.Integer(), nullable=True),
    sa.Column('yellow_cards', sa.Integer(), nullable=True),
    sa.Column('red_cards', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fixture_id', 'team_id')
    )
    op.create_index('idx_match_stats_fixture', 'match_stats', ['fixture_id'], unique=False)
    op.create_table('scorer_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('goals', sa.Integer(), server_default='0', nullable=False),
    sa.Column('assists', sa.Integer(), server_default='0', nullable=False),
    sa.Column('matches_played', sa.Integer(), server_default='0', nullable=False),
    sa.Column('position', sa.Text(), nullable=True),
    sa.Column('clean_sheets', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id')
    )
    op.create_index('idx_scorer_stats_goals', 'scorer_stats', [sa.text('goals DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_scorer_stats_goals', table_name='scorer_stats')
    op.drop_table('scorer_stats')
    op.drop_index('idx_match_stats_fixture', table_name='match_stats')
    op.drop_table('match_stats')
    op.drop_table('lineups')
    op.drop_table('goals')
    op.drop_index('idx_ai_insights_fixture', table_name='ai_insights')
    op.drop_table('ai_insights')
    op.drop_index('idx_standings_group', table_name='standings')
    op.drop_table('standings')
    op.drop_table('players')
    op.drop_index('idx_fixtures_status', table_name='fixtures')
    op.drop_index('idx_fixtures_kickoff', table_name='fixtures')
    op.drop_index('idx_fixtures_home_team', table_name='fixtures')
    op.drop_index('idx_fixtures_away_team', table_name='fixtures')
    op.drop_table('fixtures')
    op.drop_table('teams')
    op.drop_table('ingestion_runs')
    op.drop_table('external_id_map')
    # ### end Alembic commands ###
