"""add goals.assist_player_name

Revision ID: 6cd3b0cfbf31
Revises: 3067dae7d76d
Create Date: 2026-06-13 02:25:01.955454

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '6cd3b0cfbf31'
down_revision: str | None = '3067dae7d76d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goals', sa.Column('assist_player_name', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goals', 'assist_player_name')
    # ### end Alembic commands ###
