"""add fixtures.summary_synced_at

Revision ID: 707dbed85118
Revises: 6cd3b0cfbf31
Create Date: 2026-06-13 02:28:25.170261

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '707dbed85118'
down_revision: str | None = '6cd3b0cfbf31'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fixtures', sa.Column('summary_synced_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fixtures', 'summary_synced_at')
    # ### end Alembic commands ###
